"use client";

import { useEffect, useState } from "react";
import { Bell, BellOff } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

// Converts the VAPID public key (base64url, as generated by
// `npx web-push generate-vapid-keys`) into the Uint8Array format the Push
// API's subscribe() call expects.
function urlBase64ToUint8Array(base64String: string) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = atob(base64);
  return Uint8Array.from([...rawData].map((char) => char.charCodeAt(0)));
}

// Drawer control for opting in/out of Web Push notifications about content
// updates (see lib/push/send.ts, triggered from an admin's publish action).
// Writes/deletes the subscription directly via the browser Supabase
// client -- RLS's "manage own" policy on push_subscriptions (see
// supabase/migrations/0001_init_schema.sql) is what makes that safe.
export function PushSubscribeToggle() {
  const [supported, setSupported] = useState(false);
  const [subscribed, setSubscribed] = useState(false);
  const [pending, setPending] = useState(false);

  useEffect(() => {
    if (!("serviceWorker" in navigator) || !("PushManager" in window)) return;
    navigator.serviceWorker.ready.then(async (registration) => {
      setSupported(true);
      const existing = await registration.pushManager.getSubscription();
      setSubscribed(!!existing);
    });
  }, []);

  async function toggle() {
    if (pending) return;
    setPending(true);
    const supabase = createClient();

    try {
      const registration = await navigator.serviceWorker.ready;

      if (subscribed) {
        const existing = await registration.pushManager.getSubscription();
        if (existing) {
          await supabase.from("push_subscriptions").delete().eq("endpoint", existing.endpoint);
          await existing.unsubscribe();
        }
        setSubscribed(false);
        return;
      }

      const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!publicKey || !user) return;

      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicKey),
      });

      await supabase
        .from("push_subscriptions")
        .upsert(
          { user_id: user.id, subscription: subscription.toJSON() },
          { onConflict: "endpoint" }
        );
      setSubscribed(true);
    } finally {
      setPending(false);
    }
  }

  if (!supported) return null;

  return (
    <button
      type="button"
      onClick={toggle}
      disabled={pending}
      className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-neutral-700 hover:bg-neutral-100 disabled:opacity-50 dark:text-neutral-200 dark:hover:bg-neutral-800"
    >
      {subscribed ? <BellOff size={18} /> : <Bell size={18} />}
      {subscribed ? "ביטול התראות עדכונים" : "הפעלת התראות עדכונים"}
    </button>
  );
}
